defaults: &defaults
  uri: mongodb://heroku_app2569762:am2qmppc3sojlv1nllisgajsja@ds029847.mongolab.com:29847/heroku_app2569762

development:
  <<: *defaults
  database: ghsafe_development

test:
  <<: *defaults
  database: ghsafe_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: ghsafe
